package com.wangjh.blog.entity;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_record.id
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_record.parent_id
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_record.article_id
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    private Long articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_record.original_author
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    private String originalAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_record.answerer_id
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    private Long answererId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_record.answerer_username
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    private String answererUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_record.respondent_id
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    private Long respondentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_record.respondent_username
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    private String respondentUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_record.comment_date
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    private Long commentDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_record.likes
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    private Integer likes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_record.comment_content
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    private String commentContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_record.id
     *
     * @return the value of comment_record.id
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_record.id
     *
     * @param id the value for comment_record.id
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_record.parent_id
     *
     * @return the value of comment_record.parent_id
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_record.parent_id
     *
     * @param parentId the value for comment_record.parent_id
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_record.article_id
     *
     * @return the value of comment_record.article_id
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_record.article_id
     *
     * @param articleId the value for comment_record.article_id
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_record.original_author
     *
     * @return the value of comment_record.original_author
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public String getOriginalAuthor() {
        return originalAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_record.original_author
     *
     * @param originalAuthor the value for comment_record.original_author
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public void setOriginalAuthor(String originalAuthor) {
        this.originalAuthor = originalAuthor == null ? null : originalAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_record.answerer_id
     *
     * @return the value of comment_record.answerer_id
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public Long getAnswererId() {
        return answererId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_record.answerer_id
     *
     * @param answererId the value for comment_record.answerer_id
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public void setAnswererId(Long answererId) {
        this.answererId = answererId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_record.answerer_username
     *
     * @return the value of comment_record.answerer_username
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public String getAnswererUsername() {
        return answererUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_record.answerer_username
     *
     * @param answererUsername the value for comment_record.answerer_username
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public void setAnswererUsername(String answererUsername) {
        this.answererUsername = answererUsername == null ? null : answererUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_record.respondent_id
     *
     * @return the value of comment_record.respondent_id
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public Long getRespondentId() {
        return respondentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_record.respondent_id
     *
     * @param respondentId the value for comment_record.respondent_id
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public void setRespondentId(Long respondentId) {
        this.respondentId = respondentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_record.respondent_username
     *
     * @return the value of comment_record.respondent_username
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public String getRespondentUsername() {
        return respondentUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_record.respondent_username
     *
     * @param respondentUsername the value for comment_record.respondent_username
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public void setRespondentUsername(String respondentUsername) {
        this.respondentUsername = respondentUsername == null ? null : respondentUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_record.comment_date
     *
     * @return the value of comment_record.comment_date
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public Long getCommentDate() {
        return commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_record.comment_date
     *
     * @param commentDate the value for comment_record.comment_date
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public void setCommentDate(Long commentDate) {
        this.commentDate = commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_record.likes
     *
     * @return the value of comment_record.likes
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public Integer getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_record.likes
     *
     * @param likes the value for comment_record.likes
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public void setLikes(Integer likes) {
        this.likes = likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_record.comment_content
     *
     * @return the value of comment_record.comment_content
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_record.comment_content
     *
     * @param commentContent the value for comment_record.comment_content
     *
     * @mbg.generated Thu Aug 08 14:09:11 CST 2019
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }
}