package com.wangjh.blog.entity;

import lombok.Data;

@Data
public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.notifier
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    private Long notifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.notifier_name
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    private String notifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.receiver
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    private Long receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.outer_id
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    private Long outerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.outer_title
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    private String outerTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.type
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.gmt_create
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.status
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.notifier
     *
     * @return the value of message.notifier
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    public Long getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.notifier
     *
     * @param notifier the value for message.notifier
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    public void setNotifier(Long notifier) {
        this.notifier = notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.notifier_name
     *
     * @return the value of message.notifier_name
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    public String getNotifierName() {
        return notifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.notifier_name
     *
     * @param notifierName the value for message.notifier_name
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    public void setNotifierName(String notifierName) {
        this.notifierName = notifierName == null ? null : notifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.receiver
     *
     * @return the value of message.receiver
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    public Long getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.receiver
     *
     * @param receiver the value for message.receiver
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    public void setReceiver(Long receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.outer_id
     *
     * @return the value of message.outer_id
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    public Long getOuterId() {
        return outerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.outer_id
     *
     * @param outerId the value for message.outer_id
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    public void setOuterId(Long outerId) {
        this.outerId = outerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.outer_title
     *
     * @return the value of message.outer_title
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    public String getOuterTitle() {
        return outerTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.outer_title
     *
     * @param outerTitle the value for message.outer_title
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    public void setOuterTitle(String outerTitle) {
        this.outerTitle = outerTitle == null ? null : outerTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.type
     *
     * @return the value of message.type
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.type
     *
     * @param type the value for message.type
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.gmt_create
     *
     * @return the value of message.gmt_create
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.gmt_create
     *
     * @param gmtCreate the value for message.gmt_create
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.status
     *
     * @return the value of message.status
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.status
     *
     * @param status the value for message.status
     *
     * @mbg.generated Tue Aug 27 22:02:46 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}