package com.wangjh.blog.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.personal_brief
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    private String personalBrief;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar_img_url
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    private String avatarImgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.recently_landed
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    private String recentlyLanded;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.token
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    private String token;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.personal_brief
     *
     * @return the value of user.personal_brief
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    public String getPersonalBrief() {
        return personalBrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.personal_brief
     *
     * @param personalBrief the value for user.personal_brief
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    public void setPersonalBrief(String personalBrief) {
        this.personalBrief = personalBrief == null ? null : personalBrief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar_img_url
     *
     * @return the value of user.avatar_img_url
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    public String getAvatarImgUrl() {
        return avatarImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar_img_url
     *
     * @param avatarImgUrl the value for user.avatar_img_url
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    public void setAvatarImgUrl(String avatarImgUrl) {
        this.avatarImgUrl = avatarImgUrl == null ? null : avatarImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.recently_landed
     *
     * @return the value of user.recently_landed
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    public String getRecentlyLanded() {
        return recentlyLanded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.recently_landed
     *
     * @param recentlyLanded the value for user.recently_landed
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    public void setRecentlyLanded(String recentlyLanded) {
        this.recentlyLanded = recentlyLanded == null ? null : recentlyLanded.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.token
     *
     * @return the value of user.token
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.token
     *
     * @param token the value for user.token
     *
     * @mbg.generated Wed Aug 07 21:13:48 CST 2019
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }
}